### ISSUE TITLE
"Cannot read property 'primus' of undefined" when writing to room without clients

### ISSUE THREAD

**Issue by raulmt** [fadeenk/primus-rooms-redis-adapter#9]
Steps to reproduce:
1. have no clients currently connected to primus
2. write into a room (no specific client, just broadcasting to a room)
3. the adapter will receive a call to the [broadcast function](https://github.com/fadeenk/primus-rooms-redis-adapter/blob/master/lib/primus-rooms-redis-adapter.js#L158), which will try to get a primus instance from the first client. But since there are no clients, it will try to get it from undefined, and then the error "Cannot read property 'primus' of undefined"

I guess it doesn't make sense to receive a broadcast call with an empty clients array… but I understand that comes from primus itself, so maybe changing that won't be possible since it probably means to break some other adapters/client apps. So from what I see it's probably better to just consider that case before getting the primus instance [here](https://github.com/fadeenk/primus-rooms-redis-adapter/blob/master/lib/primus-rooms-redis-adapter.js#L204). Maybe just surrounding those two lines with an if:

```js
var clientsKeys = Object.keys(clients);
if (clientsKeys.length) {
  var primus = clients[clientsKeys[0]].primus;
  primus.forward.sparks(ids, transformer(data));
}
```

So not doing anything if that's not true, which is probably the correct thing to (not) do… right?

Let me know if you prefer me to send a PR, but please take a look and tell me if the approach would be ok.

Thanks!

**Comment by fadeenk** [comment]
Hi @raulmt 

Thanks for catching that! I wont be able to fix it till the weekend (work got me super busy) so you might want to do a PR if you want this live ASAP.
